### ISSUE TITLE
Combine Axis & Actions

### ISSUE THREAD

**Issue by shawticus** [xr3ngine/ecsy-input#15]
Right now, axis and action are different -- the only different between them, really, is that actions are discrete states (STARTED, ENDED) and axis values are continues (x: 342, y: 934).

How do we combine these in a way that is comfortable for the user? Do we need to?

(If we are going to rename, we should rename to Axis, not Action.)

**Comment by XiaNi** [comment]
it probably makes sens, i think some buttons(like triggers on gamepad) could have several states of pressed (or even full range from 0.0 to 1.0)
we can treat buttons like axis that usually jumps from 0 to 1 and back.

**Comment by shawticus** [comment]
I agree with this.
Axis types can be: Button | Axis1D | Axis2D | Axis3D
Button is same as axis1d basically but values are 0 and 1.

**Comment by shawticus** [comment]
I ended up doing this (and implementing a new behavior generally) -- if you're already worked on it, cool, I'd like to see, but big change coming.
